# Generated by Django 4.0 on 2021-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=16)),
                ('gnere', models.CharField(max_length=16)),
                ('year', models.IntegerField(default=2000)),
                ('actors', models.CharField(max_length=16)),
                ('duration', models.CharField(max_length=16)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
