# Generated by Django 4.0 on 2021-12-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovieapp', '0002_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='id',
            new_name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gnere',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='moviename',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
        migrations.AddField(
            model_name='movies',
            name='backdrop_path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='overview',
            field=models.CharField(default='no overview', max_length=256),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='title', max_length=64),
        ),
    ]
