# Generated by Django 4.0 on 2021-12-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovieapp', '0003_delete_users_rename_id_movies_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
