# Generated by Django 4.0 on 2021-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovieapp', '0004_alter_movies_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.CharField(default='no overview', max_length=1024),
        ),
    ]
