# Generated by Django 4.0 on 2021-12-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovieapp', '0005_alter_movies_overview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
