# Generated by Django 4.0 on 2021-12-19 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymovieapp', '0006_alter_movies_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
