# Generated by Django 4.0 on 2021-12-19 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymovieapp', '0007_movies_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
